# -*- coding: utf-8 -*-
"""Project ML - SLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BGkvC7qnvZU8hd8YWcijVgjssLa7BuFX
"""

!pip install flask-ngrok

import pandas as pd
import numpy as np

class SingleLayerPerceptron:
    
  def learning(dataTest):
    # Import Dataset
    url = "https://raw.githubusercontent.com/atjhoendz/single-layer-perceptron/main/iris-data.xlsx"
    dataX = pd.read_excel(url, usecols=[0, 1, 2, 3])
    dataY = pd.read_excel(url, usecols=[5])
    x = np.array(dataX, np.float32)
    y = np.squeeze(np.array(dataY, np.float32))

    # Deklarasi nilai awal
    NUM_FEATURES = 4
    NUM_ITER = 100
    learning_rate = 0.1
    W = np.zeros(NUM_FEATURES, np.float32)
    b = np.zeros(1, np.float32)

    # Proses Learning
    for i in range(NUM_ITER):
      y_pred = np.dot(x, W) + b

      #activation sigmoid
      y_pred[y_pred > 0] = 1
      y_pred[y_pred <= 0] = 0

      err = y - y_pred
      
      if np.sum(err) == 0:
        break
      
      delta_W = learning_rate * np.dot(np.transpose(x), err)
      delta_b = learning_rate * np.sum(err)
      W = W + delta_W
      b = b + delta_b

      print ("Iterasi ke-" + str(i), err, W, b)
    
    # Proses Testing
    y_test = np.dot(dataTest, W) + b
    y_test = 1 if y_test > 0 else 0

    return y_test

from flask_ngrok import run_with_ngrok
from flask import Flask, render_template, request

app = Flask(__name__, template_folder='drive/My Drive/Colab Notebooks/')
run_with_ngrok(app)

@app.route("/")
def home():
  return render_template('iris-prediction.html')

@app.route("/submit", methods = ['POST'])
def submit():
  if request.method == 'POST':
    p_sepal = request.form['panjangSepal']
    l_sepal = request.form['lebarSepal']
    p_petal = request.form['panjangPetal']
    l_petal = request.form['lebarPetal']
    
    arr = [float(p_sepal), float(l_sepal), float(p_petal), float(l_petal)]

    SLP = SingleLayerPerceptron
    result = SLP.learning(arr)
    
    return render_template('iris-prediction.html', result=result, show=1, data=arr)

if __name__ == '__main__':
  app.run()